# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Main text of home
name: Lucas Stoque
bio: Front End Developer

# Site settings
title: Lucas Stoque - Desenvolvedor Front End
email: stoque@live.com
description: "Um blog de um desenvolvedor frontend que ama novas técnologias"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stoque.github.io" # the base hostname & protocol for your site
twitter_username: ostoque
github_username:  stoque

# Build settings
markdown: kramdown
permalink: /:title/

# Links
links:
  - title: Blog
    url: /
  - title: Sobre
    url: /about

# Exclude node and source
exclude: ['package.json', 'gulpfile.js', 'README.md', 'src', 'node_modules']

